### ISSUE TITLE
Actividad 10 - practica comando de voz

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/actividad-10-practica-de-comando-de-voz-promastergamer#1]

**Comment by Heidi-19** [comment]
[Actividad 10 - comando de voz.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-practica-de-comando-de-voz-promastergamer/files/15359722/Actividad.10.-.comando.de.voz.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...Calificación 20
